#!/usr/bin/env bash
set -Eeuo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_repo="${EMIL_SKILL_REPO:-https://github.com/pproenca/dot-skills.git}"
source_ref="${EMIL_SKILL_REF:-master}"
source_path="skills/.experimental/emilkowal-animations"
destination_dir="$repo_dir/agents/skills/emilkowal-animations"
temporary_dir="$(mktemp -d /tmp/configs-emil-animations.XXXXXX)"

cleanup() {
  rm -rf "$temporary_dir"
}
trap cleanup EXIT

for command in git rsync; do
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "$command is required to update the animation skill" >&2
    exit 1
  fi
done

git clone \
  --quiet \
  --depth=1 \
  --filter=blob:none \
  --branch "$source_ref" \
  --sparse \
  "$source_repo" \
  "$temporary_dir/source"

git -C "$temporary_dir/source" sparse-checkout set --no-cone \
  "/$source_path/" \
  "/LICENSE"

source_dir="$temporary_dir/source/$source_path"
if [[ ! -f "$source_dir/SKILL.md" ]]; then
  echo "Animation skill is missing SKILL.md" >&2
  exit 1
fi

mkdir -p "$destination_dir"
rsync --archive --delete "$source_dir/" "$destination_dir/"
cp "$temporary_dir/source/LICENSE" "$destination_dir/LICENSE"

source_commit="$(git -C "$temporary_dir/source" rev-parse HEAD)"
printf '%s\n' \
  '# Generated by agents/sync-emil-animations.sh' \
  "ref=$source_ref" \
  "commit=$source_commit" \
  >"$repo_dir/agents/emil-animations.lock"

printf 'Pinned animation skill at %s\n' "$source_commit"
