#!/usr/bin/env bash
set -Eeuo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_repo="${SKILLS_SOURCE_REPO:?Set SKILLS_SOURCE_REPO to the source Git repository}"
source_label="${SKILLS_SOURCE_LABEL:?Set SKILLS_SOURCE_LABEL to the branding to remove}"
source_ref="${SKILLS_SOURCE_REF:-main}"
skills_dir="$repo_dir/agents/skills"
temporary_dir="$(mktemp -d /tmp/configs-agent-skills.XXXXXX)"

cleanup() {
  rm -rf "$temporary_dir"
}
trap cleanup EXIT

for command in git perl rsync; do
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "$command is required to update agent skills" >&2
    exit 1
  fi
done

skills=(
  writing-quality-code
  interface-polish
  git-conventions
)

git clone \
  --quiet \
  --depth=1 \
  --filter=blob:none \
  --branch "$source_ref" \
  --sparse \
  "$source_repo" \
  "$temporary_dir/source"

git -C "$temporary_dir/source" sparse-checkout set \
  "${skills[@]/#/.agents/skills/}"

mkdir -p "$skills_dir"

for skill in "${skills[@]}"; do
  source_dir="$temporary_dir/source/.agents/skills/$skill"
  destination_dir="$skills_dir/$skill"

  if [[ ! -f "$source_dir/SKILL.md" ]]; then
    echo "Source skill is missing SKILL.md: $skill" >&2
    exit 1
  fi

  mkdir -p "$destination_dir"
  rsync --archive --delete "$source_dir/" "$destination_dir/"
  printf 'Updated: %s\n' "$skill"
done

export SKILLS_SOURCE_LABEL="$source_label"
find "${skills[@]/#/$skills_dir/}" -type f -exec perl -pi -e '
  s/\Q$ENV{SKILLS_SOURCE_LABEL}\E(?:\x27s)?/Personal/ig;
  s/Personal\x27s/personal/g;
  s/\@personal/\@app/ig;
  s/^# Personal Writing Quality Code$/# Writing Quality Code/;
  s/^# Personal Interface Polish$/# Interface Polish/;
  s/^# Personal Git Conventions$/# Git Conventions/;
  s/for Personal business/for business/g;
  s/Personal Effect/Effect/g;
  s/Personal server-side/server-side/g;
  s/Personal code/code/g;
  s/Personal default/Default/g;
  s/personal standard/the standard/g;
  s/[ \t]+$//;
' {} +

source_commit="$(git -C "$temporary_dir/source" rev-parse HEAD)"
printf '%s\n' \
  '# Generated by agents/sync-agent-skills.sh' \
  "ref=$source_ref" \
  "commit=$source_commit" \
  >"$repo_dir/agents/agent-skills.lock"

printf 'Pinned personal skills at %s\n' "$source_commit"
